title = "Daily Grind"
baseURL = "https://dreamy-golick-3406f2.netlify.app"
theme = "bilberry-hugo-theme"

# Generate the robots.txt file for SEO
enableRobotsTXT = true

# Change to one of your content languages definded at the end.
DefaultContentLanguage = "en"

# Enable / Disable Google Analytics statistics for your site
googleAnalytics = ""

# Enable / Disable comments on the articles via Disqus.
disqusShortname = "dailygrind-1"

# Enable / Disable open link with a new tab.
[blackfriday]
  hrefTargetBlank = false

[params]
  # Custom CSS / JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = []
  js_modules = []

  # Description and meta data for the search engines
  author = "Gunjan Shah"
  description = "Daily Grind is a personal blog which shares unique takeaways from our mundane life.This may help the readers understand themselves more fully and help them lead a better, more fulfilling life."
  keywords = "blog,personal,life,journey,work,mind,spiritual,advice,path,motivation,grind,existence,satisfaction,fulfillment"

  # How many articles should be displayed at once?
  paginate = 7

  # Enable / Disable MathJax
  enable_mathjax    = false

  # Enable / Disable algolia search
  algolia_search    = true
  algolia_appId     = "1Q7CYV6RDU"
  algolia_apiKey    = "3f98ac39abf8894eaa5bd6e945e6560a"
  algolia_indexName = "dailygrind"
    # Set this option to false if you want to search within all articles in all languages at once
    algolia_currentLanguageOnly = true

  # Media configuration
    # let hugo automatically resize and crop your images to the correct sizes
    # NB: When enabled the image files get renamed by adding additional information,
    #     even if the image has the correct sizes.
    resizeImages = true

  # Header configuration
    # your subtitle if you want to use any
    subtitle = "Staying curious since the 90's.."

    # if you want to use gravatar for the header image
    # gravatarEMail = "code@lednerb.de"

    # set an path to the image file you want to use | overwrites gravatar
     customImage = "cover.jpg"

    # define the icon you want to use for the overlay for the customImage or gravatar.
    # overlayIcon = "fa-home"

    # always display the top navigation (with pages and search) on non-mobile screens
    permanentTopNav = false

    # always display the top navigation when scrolling
    # works only with permanentTopNav = true
    stickyNav = false

    # show a language chooser in the header
    showHeaderLanguageChooser = true

  # Content configuration
    # Enable an optional pinned page to display at the top of the index
    # pinnedPost = "/content/github/"
    # Set to true to pin only to the first page, false to all pages
    # pinOnlyToFirstPage = true

    # enable automatical localization of the article's PublishedDate with momentjs
    enableMomentJs = true

    # customize the date format | only works if momentjs is disabled | only works with English month names
    # you can customize it with the options you find here:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    dateFormat = "2006-01-02"

    # display the estimated reading time for an article
    showReadingTime = true

  # Footer configuration
    showFooter = true

    # How many articles should be displayed at latest posts in the footer?
    # Set to -1 to hide the 'Latest Posts' column
    amountLatestPostsInFooter = 7

    # How many categories should be displayed in the footer section?
    # Set to -1 to hide the 'Categories' column
    amountCategoriesInFooter = 7

    # show a language chooser in the footer
    showFooterLanguageChooser = true

    # social media profile urls for the footer links
    showSocialMedia = true

    # define your links with FontAwesome 5 (only free icons are supported)
    # all icons https://fontawesome.com/icons?d=gallery&m=free
    # brand icons https://fontawesome.com/icons?d=gallery&s=brands&m=free
    socialMediaLinks = [
      { link = "https://twitter.com/Gunjan19023325", icon = "fab fa-twitter" },
      { link = "https://github.com/gunjan-shah", icon = "fab fa-github" },
    ]

    # credits line configuration
    copyrightBy = "by Gunjan Shah"
    copyrightUseCurrentYear = true  # set to true to always display the current year in the copyright
    copyrightYearOverride = "2017"
    copyrightUrl = "https://github.com/gunjan-shah"
    creditsText = "Daily Grind"
    creditsUrl = "https://github.com/gunjan-shah"



# don't change anything below
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"

[outputs]
  home = [ "HTML", "JSON", "RSS" ]
  page = [ "HTML" ]

